# -*- coding: utf-8 -*-
"""breast_cancer_rf_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h8XybDomdXOrE1XfIJT1kQqHYP0xlfjw
"""

# 2차 n_estimators 파라미터 변경 실험 (10 → 100)

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

# ① 데이터셋 로드
cancer = load_breast_cancer()
X = cancer.data
y = cancer.target

print("=== 데이터셋 정보 ===")
print(f"전체 샘플 수: {X.shape[0]}")
print(f"특성(feature) 수: {X.shape[1]}")
print(f"클래스: {cancer.target_names}")

# ② Train / Test Split (80:20)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
print(f"\n훈련 데이터: {X_train.shape[0]}개")
print(f"테스트 데이터: {X_test.shape[0]}개")

# ③ 파라미터 변경 실험: n_estimators 10 vs 100 비교
print("\n=== 파라미터 실험: n_estimators 비교 ===")
for n in [10, 50, 100]:
    model = RandomForestClassifier(n_estimators=n, random_state=42)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    acc = metrics.accuracy_score(y_test, y_pred)
    print(f"n_estimators={n:>3}  →  정확도: {acc:.4f}  ({acc*100:.2f}%)")

# ④ 최적 파라미터(n_estimators=100)로 최종 결과 출력
print("\n=== 최종 모델 결과 (n_estimators=100) ===")
best_model = RandomForestClassifier(n_estimators=100, random_state=42)
best_model.fit(X_train, y_train)
y_pred_best = best_model.predict(X_test)
best_acc = metrics.accuracy_score(y_test, y_pred_best)

print(f"최종 정확도(Accuracy): {best_acc:.4f}  ({best_acc*100:.2f}%)")
print("\n분류 보고서:")
print(metrics.classification_report(y_test, y_pred_best, target_names=cancer.target_names))