# -*- coding: utf-8 -*-
"""breast_cancer_rf_v3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16PHk-BAeGvh8alFKO9rejcjgJSNpmF-Q
"""

# 3차 다중 모델 비교 (RandomForest / SVM / KNN)

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

# ① 데이터셋 로드
cancer = load_breast_cancer()
X = cancer.data
y = cancer.target

# ② Train / Test Split (80:20)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ③ 모델 정의
models = {
    "Random Forest (n=100)": RandomForestClassifier(n_estimators=100, random_state=42),
    "SVM":                   SVC(random_state=42),
    "KNN (k=6)":             KNeighborsClassifier(n_neighbors=6),
}

# ④ 학습 및 정확도 비교 출력
print("=== 모델별 정확도 비교 ===")
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    acc = metrics.accuracy_score(y_test, y_pred)
    print(f"{name:<30} 정확도: {acc:.4f}  ({acc*100:.2f}%)")

# ⑤ 최고 성능 모델 상세 결과 (Random Forest)
print("\n=== 최고 성능 모델 상세 결과 (Random Forest) ===")
best = RandomForestClassifier(n_estimators=100, random_state=42)
best.fit(X_train, y_train)
y_pred_best = best.predict(X_test)
print(metrics.classification_report(y_test, y_pred_best, target_names=cancer.target_names))