# -*- coding: utf-8 -*-
"""breast_cancer_rf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kXVz7p97XarEav3Sq58_oLR3NMw9RncL
"""

# 유방암 데이터 분류 (Random Forest)
# 데이터셋: load_breast_cancer (sklearn)
# 모델: RandomForestClassifier

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

# ① 데이터셋 로드
cancer = load_breast_cancer()
X = cancer.data
y = cancer.target

print("=== 데이터셋 정보 ===")
print(f"전체 샘플 수: {X.shape[0]}")
print(f"특성(feature) 수: {X.shape[1]}")
print(f"클래스: {cancer.target_names}")  # ['malignant', 'benign']

# ② Train / Test Split (80:20)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
print(f"\n훈련 데이터: {X_train.shape[0]}개")
print(f"테스트 데이터: {X_test.shape[0]}개")

# ③ 모델 학습 (n_estimators=10 : 초기 실험)
model = RandomForestClassifier(n_estimators=10, random_state=42)
model.fit(X_train, y_train)

# ④ 예측 및 정확도 출력
y_pred = model.predict(X_test)
accuracy = metrics.accuracy_score(y_test, y_pred)

print("\n=== 학습 결과 (n_estimators=10) ===")
print(f"정확도(Accuracy): {accuracy:.4f}  ({accuracy*100:.2f}%)")
print("\n분류 보고서:")
print(metrics.classification_report(y_test, y_pred, target_names=cancer.target_names))